extends: default
# base:
#     # line-height: $base-line-height-length / $base-font-size
#     line-height-length: 50
#     line-height: 2.5
# sidebar:
#     background-color: transparent
# heading:
#     h1-font-size: $base-font-size * 2
#     h2-font-size: $base-font-size * 1.6
#     h3-font-size: $base-font-size * 1.2
# literal:
#     font-color: #657d8f