// :autofit-option:
:stem: latexmath
:toc:

= Colbyn's Calculus Notes

== Derivatives

=== Limit Definition of A Derivative

[latexmath]
++++
f^\prime(x) =
\lim_{h \to 0} \frac{f(a + h) - f(a)}{h} =
\lim_{x \to a} \frac{f(a) - f(x)}{a - x} =
\frac{dy}{dx}f(x) =
\frac{d}{dx}f(x)
++++

==== Formal Limit Definition of A Derivative

Derivative of latexmath:[f(x)=|x|] using the formal 'limit definition of a derivative':

[latexmath]
++++
\begin{equation}
\begin{split}
f(x) & = |x| \\
f^\prime(a) & = \lim_{h \to 0} \frac{f(a + h) - f(a)}{h} \\
     & = \lim_{h \to 0} \frac{|a + h| - |a|}{h} \cdot \frac{|a + h| + |a|}{|a + h| + |a|} \\
     & = \lim_{h \to 0} \frac{|a + h|^2 - |a|^2}{h \cdot (|a + h| + |a|)} \\
     & = \lim_{h \to 0} \frac{(a + h)^2 - a^2}{h (|a + h| + |a|)} \\
     & = \lim_{h \to 0} \frac{a^2 + 2ah + h^2 - a^2}{h (|a + h| + |a|)} \\
     & = \lim_{h \to 0} \frac{2ah + h^2}{h (|a + h| + |a|)} \\
     & = \lim_{h \to 0} \frac{h \cdot (2a + h)}{h \cdot (|a + h| + |a|)} \\
     & = \lim_{h \to 0} \frac{2a + h}{|a + h| + |a|} \\
     & = \frac{2a + (0)}{|a + (0)| + |a|} \\
     & = \frac{2a}{|a| + |a|} \\
     & = \frac{2a}{2|a|} \\
     & = \frac{2a}{2|a|} \cdot \frac{|a|}{|a|} \\
     & = \frac{2a|a|}{2|a|^2} \\
     & = \frac{2a|a|}{2a^2} \\
     & = \frac{|a|}{a} \\
f^\prime(x) &= \frac{|x|}{x}
\end{split}
\end{equation}
++++

Derivative of latexmath:[f(x)=|x|] using an `alternative limit definition of a derivative':

[latexmath]
++++
\begin{equation}
\begin{split}
f(x) & = |x| \\
f^\prime(a) & = \lim_{x \to a} \frac{f(a) - f(x)}{a - x} \\
    & = \lim_{x \to a} \frac{|a| - |x|}{a - x} \cdot \frac{|a| + |x|}{|a| + |x|} \\
    & = \lim_{x \to a} \frac{|a|^2 - |x|^2}{(a - x) \cdot (|a| + |x|)} \\
    & = \lim_{x \to a} \frac{(a)^2 - (x)^2}{(a - x) \cdot (|a| + |x|)} \\
    & = \lim_{x \to a} \frac{(a - x) \cdot (a + x)}{(a - x) \cdot (|a| + |x|)} \\
    & = \lim_{x \to a} \frac{a + x}{|a| + |x|} \\
    & = \frac{a + (a)}{|a| + |(a)|} \\
    & = \frac{2a}{2|a|} \\
    & = \frac{a}{|a|} \cdot \frac{|a|}{|a|} \\
    & = \frac{a|a|}{|a|^2} \\
    & = \frac{a|a|}{a^2} \\
    & = \frac{|a|}{a} \\
f^\prime(x) &= \frac{|x|}{x}
\end{split}
\end{equation}
++++


=== Tangent Line

[latexmath]
++++
\begin{equation}
\begin{split}
y - y_1 &= f^\prime(x_1)(x-x_1) \\
y &= mx + b
\end{split}
\end{equation}
++++


==== Alternative Overview

[latexmath]
++++
y = mx + b
++++

Generally, there are three things you will need when given some latexmath:[f(x)]:

* The value of latexmath:[x] (usually provided to you)
* The value of latexmath:[y] or latexmath:[f(x)] (if it's not provided to you, just plug it in)
* The value of m (i.e. the slope, such as the value from latexmath:[f^\prime(x)])
* Once you have latexmath:[m], then solve for latexmath:[b] by plugging in some latexmath:[(x, y)] into your latexmath:[y = mx + b] equation.


=== Normal Line


The slope of the normal line is the negative reciprocal of the slope of the tangent line. Everything else is the same as the tangent line.

[latexmath]
++++
\begin{equation}
\begin{split}
y - y_1 &= -\frac{1}{f^\prime(x_1)} (x-x_1) \\
y &= -\frac{1}{m}x + b
\end{split}
\end{equation}
++++


=== Derivative Continuity

==== Continuous Piecewise Function







